server:
  port: 8081
  servlet:
    context-path: /javasm
#当前项目访问路径 +项目名
spring:
  thymeleaf:
    cache: false
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
 #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: xiafei
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false  #redis的配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: javasm
    database: 1
  #连接超时时间 单位ms
    timeout:
     seconds: 3000ms
    jedis:
      pool:
        #连接池最大空闲连接，默认值也是8
        max-idle: 8
        #连接池最小空闲连接，默认值也是0
        min-idle: 0
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 10000ms
  data:
    solr:
      host: http://192.168.14.199:8983/solr

mybatis:
  mapper-locations: classpath:com/javasm/*/mapper/*.xml
#  用来扩展
#  config-location: classpath:mybatis-config.xml
